_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 1ffaa482-b020-4d99-8a07-29d2dd9e51e2
name: 'Ryan Buenconsejo'
mail: ryan.buen703@icloud.com
slogan: ''
page:
  403: ''
  404: ''
  front: /
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
